# GitHub actions workflow.
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

name: Alpine

on:
  pull_request:
  push:
    branches: main

jobs:
  build:
    strategy:
      matrix:
        cc: [gcc, clang]
        valgrind: [valgrind, vanilla]
      fail-fast: false
    runs-on: ubuntu-latest
    container: alpine:latest
    env:
      CC: ${{ matrix.cc }}
    steps:
      - name: Install dependencies
        run: |
          apk --no-cache add meson pkgconf boost-dev python3-dev build-base valgrind ${{ matrix.cc }}

      - uses: actions/checkout@v4

      - name: Configure
        run: |
          case "${{ matrix.cc }}" in
            gcc)
              export CC=gcc
              export CXX=g++
              ;;
            clang)
              export CC=clang
              export CXX=clang++
              ;;
          esac

          meson setup -Dtest=true -Dwerror=true build

      - name: Build
        run: |
          ninja -C build

      - name: Test
        run: |
          case "${{ matrix.valgrind }}" in
            valgrind)
              args="--wrapper valgrind"
              ;;
            vanilla)
              ;;
          esac

          meson test -C build --print-errorlogs ${args}
