name: lint

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    container: ghcr.io/jannik2099/pms-utils-gentoo-ci:latest

    steps:
      - uses: actions/checkout@v4

      - name: configure
        run: |
          . /etc/profile
          CC=clang CXX=clang++ meson setup -Dtest=true -Dfuzz=true -Db_lundef=false build

      - name: analyze
        run: |
          . /etc/profile
          ninja -C build clang-tidy
