name: "docs"

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    name: Build documentation
    permissions:
      contents: read
      deployments: write
    runs-on: ubuntu-latest
    container: ghcr.io/jannik2099/pms-utils-gentoo-ci:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure venv
        run: |
          python -m venv .venv
          .venv/bin/pip install Sphinx sphinx-toolbox sphinx-rtd-theme enum-tools

      - name: Configure
        run: |
          . .venv/bin/activate
          meson setup -Dtest=false -Ddocs=true -Dbuildtype=debugoptimized build

      - name: Build
        run: |
          . .venv/bin/activate
          meson compile -C build docs

      - name: Test
        run: |
          . .venv/bin/activate
          meson test -C build

      - name: Install npm
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Upload docs
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy build/subprojects/bindings-python/docs --project-name=pms-utils --branch=${{ github.ref_name }}
